version: "3"

services:
  terraform_backend:
    image: ghcr.io/nimbolus/terraform-backend
    build: .
    environment:
      STORAGE_FS_DIR: /states
      # change the key before using the backend
      KMS_KEY: jwS6UpASMOWpEmFn7C6I47BlmPt4cpdmYLKd2E7a4Zk=
      REDIS_ADDR: redis:6379
      LOCK_BACKEND: redis
    ports:
      - "8080:8080"
      - "127.0.0.1:8081:8081"
    volumes:
      - states:/states
    links:
      - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  minio:
    image: minio/minio:RELEASE.2022-04-30T22-23-53Z # a version that still supports fs storage
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
      MINIO_CONSOLE_ADDRESS: :9001
    command: server /storage
    ports:
      - "9000:9000"
      - "9001:9001"
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx
      - ./nginx-certs:/etc/ssl/private

volumes:
  states:
